[[redirects]]
  from = "https://leotransferbuzios.com.br/*"
  to = "https://leotransferbuzios.netlify.app/:splat"
  status = 200
  force = true

[[redirects]]
  from = "https://www.leotransferbuzios.com.br/*"
  to = "https://leotransferbuzios.netlify.app/:splat"
  status = 200
  force = true
